name: deploy


on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      # - run: npm run export
      
      - run: REPO_NAME=${{github.event.repository.name}} DEPLOY_URL=${{github.events.repository.html_url}} yarn export
      # - run: PATH_PREFIX=${{github.event.repository.name}} yarn build
      # - run: mv __admin public/
      # for access _next directory
      - name: Add nojekyll
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
